import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const About: NextPage = () => {
  return (
    <div className={styles.container}>
       <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About page</h1>

        <div className={styles.grid}>
          <Link passHref href="/">
            <a className={styles.card}>
              <h2>Home &rarr;</h2>
              <p>Go to home Page.</p>
            </a>
          </Link>

          <Link passHref href="/project">
            <a className={styles.card}>
              <h2>Project &rarr;</h2>
              <p>Go to Project Page!</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default About;
