import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> Next.js Github Page!</h1>

        <div className={styles.grid}>
          <Link className={styles.card} passHref href="/project">
            <h2>Project &rarr;</h2>
            <p>Go to Project Page.</p>
          </Link>

          <Link className={styles.card} passHref href="/about">
            <h2>About &rarr;</h2>
            <p>Go to About Page!</p>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
